name: photo_challenge
description: Network Photo Challenge for KCD
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_route: ^7.8.0
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.2
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.8.5
  csv: ^5.0.2
  equatable: ^2.0.5
  file_picker: ^5.3.3
  firebase_auth: ^4.7.3
  firebase_core: ^2.15.1
  firebase_storage: ^11.2.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  google_fonts: ^6.0.0
  http: ^1.1.0
  image_picker: ^1.0.2
  image_picker_web: ^3.1.1
  intl: ^0.18.0
  rxdart: ^0.27.7
  shared_preferences: ^2.2.0
  url_strategy: ^0.2.0

dev_dependencies:
  auto_route_generator: ^7.3.1
  bloc_test: ^9.1.2
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
